version: '3.7'

# mysql simple and express

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped


  app:
    build: .
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

